POST http://localhost:3001/api/auth/register
Content-Type: application/json

{
  "name":"Oscar Register",
  "email":"register@test.com",
  "password":"test123"
}

#####
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
  "email":"admin@test.com",
  "password":"test123"
}

####
GET http://localhost:3000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQWRtaW4iLCJfaWQiOiI1ZGFkMjJhMjI1Zjg4NDAzYThlMjdkYWQiLCJuYW1lIjoiYWRtaW4gMSIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJfX3YiOjAsImlhdCI6MTU3MTYzNjEwNSwiZXhwIjoxNTcxNjM5NzA1fQ.dp-PlSW8v8BjWigYhDWAteQ7nW252HBosmOp___d-q4

###
POST http://localhost:3000/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQWRtaW4iLCJfaWQiOiI1ZGFkMjJhMjI1Zjg4NDAzYThlMjdkYWQiLCJuYW1lIjoiYWRtaW4gMSIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJfX3YiOjAsImlhdCI6MTU3MTYzNjEwNSwiZXhwIjoxNTcxNjM5NzA1fQ.dp-PlSW8v8BjWigYhDWAteQ7nW252HBosmOp___d-q4

{
  "name":"customer 3",
  "email":"customer3@test.com",
  "role": "Customer",
  "password":"test123"
}
###
GET  http://localhost:3000/api/users/5dad36abf4664436a4d1fc4a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQWRtaW4iLCJfaWQiOiI1ZGFkMjJhMjI1Zjg4NDAzYThlMjdkYWQiLCJuYW1lIjoiYWRtaW4gMSIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJfX3YiOjAsImlhdCI6MTU3MTYzNjEwNSwiZXhwIjoxNTcxNjM5NzA1fQ.dp-PlSW8v8BjWigYhDWAteQ7nW252HBosmOp___d-q4

### 
PUT http://localhost:3000/api/users/5dad36abf4664436a4d1fc4a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQWRtaW4iLCJfaWQiOiI1ZGFkMjJhMjI1Zjg4NDAzYThlMjdkYWQiLCJuYW1lIjoiYWRtaW4gMSIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJfX3YiOjAsImlhdCI6MTU3MTYzNjEwNSwiZXhwIjoxNTcxNjM5NzA1fQ.dp-PlSW8v8BjWigYhDWAteQ7nW252HBosmOp___d-q4

{
  "name":"customer 3 updated",
  "email":"test.com"
}

### 
DELETE http://localhost:3000/api/users/5dad358565189914d4a25edd
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQWRtaW4iLCJfaWQiOiI1ZGFkMjJhMjI1Zjg4NDAzYThlMjdkYWQiLCJuYW1lIjoiYWRtaW4gMSIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJfX3YiOjAsImlhdCI6MTU3MTYzNjEwNSwiZXhwIjoxNTcxNjM5NzA1fQ.dp-PlSW8v8BjWigYhDWAteQ7nW252HBosmOp___d-q4

####
GET http://localhost:3000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQ3VzdG9tZXIiLCJfaWQiOiI1ZGFkMjFiNTZlMGUwNjMzMzg3NGU1YmUiLCJuYW1lIjoidGVzdCBSZWlub3NhIiwiZW1haWwiOiJ0ZXN0QHRlc3QuY29tIiwiX192IjowLCJpYXQiOjE1NzE2Mjc1MDIsImV4cCI6MTU3MTYzMTEwMn0.NEqizCuhSOyiyqz9zCZ2rTtbkV8N_4JkycRR7UCPMvk